### ISSUE TITLE
Unable to run XAFS_GUI.PY with error -- ModuleNotFoundError: No module named 'larch_plugins'

### ISSUE THREAD

**Issue by duoduoss** [laumiulun/EXAFS-Neo-Public#1]
Hello,

I tried to run "python XAFS_GUI.py", but got the following errons. The larch I installed is the newest version 0.9.58, and the python is 3.7.12. 
Traceback (most recent call last):
  File "XAFS_GUI.py", line 37, in <module>
    import EXAFS_Analysis
  File "C:\Users\........\EXAFS-Neo-Public\gui\EXAFS_Analysis.py", line 14, in <module>
    from larch_plugins.xafs import xftf
ModuleNotFoundError: No module named 'larch_plugins'

Could you please help with this issues? 

Thanks in advance,
Best regards,
Yang

**Comment by jterry94** [comment]
We will take a look. It is possible that they did away with larch_plugins in the new version of larch. 

Jeff

**Comment by laumiulun** [comment]
Hi @duoduoss  I pushed a hot fix to fix it with the latest version of larch (0.9.58). Feel free to update it by `git pull` and then `python setup.py install`. In the future we will constrain it to a specific version until we further tested it 

Best,
Andy

**Comment by duoduoss** [comment]
Thank you all very much! Now I can open the GUI！
