### ISSUE TITLE
Error report 

### ISSUE THREAD

**Issue by otden** [laumiulun/EXAFS-Neo-Public#2]
Dear Dr. Lau,
I send an error report for installing XAFS_GUI.py.
I appreciate if you can give an advice to solve the error.
Please find the details from the attached file.

Best,
Den
[Error.txt](https://github.com/laumiulun/EXAFS-Neo-Public/files/11902990/Error.txt)

**Comment by laumiulun** [comment]
Hi @otden, are you running this in a VM? I need more information regarding how to reproduce this error?

Andy

**Comment by otden** [comment]
Dear Andy,

Thank you for your reply.
I don't use a VM but I am running the EXAFS Neo on the terminal of Mac OS X(Catalina10.15.7).

OTei

**Comment by laumiulun** [comment]
I guess I need some specific instruction from you regarding this error you encountering.

Are you just running the gui by itself? What do you see when you run `python XAFS_GUI.py`?

**Comment by otden** [comment]
Thank you for your reply.
I attached some error message after updating EXAFS-NEO and running python3 XAFS_GUI.py.
I hope it helps you.
[Error_gui.txt](https://github.com/laumiulun/EXAFS-Neo-Public/files/11953599/Error_gui.txt)

OTei

**Comment by laumiulun** [comment]
Please try `conda install psutil` in EXAFS environment.

**Comment by otden** [comment]
Dear Andy,

I think the problem was solved.

Cheers!
